### ISSUE TITLE
V0.5 Milestone

### ISSUE THREAD

**Issue by nmezhenskyi** [nmezhenskyi/rcs#1]
## Checklist for releasing Version 0.5.0:
- [x] Basic cache implementation
- [x] HTTP API implementation
- [x] GRPC API implementation
- [x] Native API implementation
- [x] SSL support
- [x] Logging
- [x] Unit tests
- [x] Documentation
- [x] Test build in Docker

**Comment by nmezhenskyi** [comment]
Released.
