### ISSUE TITLE
V1.0 Milestone

### ISSUE THREAD

**Issue by nmezhenskyi** [nmezhenskyi/rcs#2]
- [x] - Expiration time for cached items & clean up routine
- [ ] - Optimize request reading buffer in `nativesrv`
- [ ] - Serialization to disk (state snapshots)
- [ ] - Examples of interfacing with HTTP, gRPC, and Native APIs
- [ ] - Benchmark APIs
- [ ] - Add WebSocket support (?)
- [x] - Multi-stage builds for Dockerfile
- [x] - Build tags to opt-out from HTTP and/or gRPC APIs
